include: package:lints/recommended.yaml

linter:
  rules:
    avoid_renaming_method_parameters: false
    always_use_package_imports: true
    avoid_print: true
    always_declare_return_types: true

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/**.g.dart
    - lib/**.config.dart
    - lib/**.freezed.dart
    - test/mocks.mocks.dart
  errors:
    missing_required_param: error
    parameter_assignments: warning
    missing_return: error
    todo: ignore

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    # dart
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-immediate-return
    - prefer-match-file-name:
      exclude:
        - main.dart
      severity:
        - error
    - no-object-declaration
    - no-magic-number
    - avoid-unused-parameters
    - prefer-async-await
    - avoid-global-state
    - avoid-throw-in-catch-block
    - avoid-non-null-assertion
    - avoid-nested-conditional-expressions
    - prefer-correct-type-name:
        min-length: 3
  anti-patterns:
    - long-method
    - long-parameter-list